<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",276,305);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",345,403);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",713,748);
$z[4][4]['filename']="head.htm";
$z[5]=Array("sql"," \r\n[field:content/] \r\n",936,1036);
$z[5][4]['sql']="Select content from dede_arctype where id=~typeid~";
$z[6]=Array("field","",1192,1221);
$z[6][4]['name']="position";
$z[7]=Array("field","",1384,1403);
$z[7][4]['name']="title";
$z[8]=Array("field","",1433,1489);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[9]=Array("field","",1520,1547);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",1571,1594);
$z[10][4]['name']="id";
$z[11]=Array("field","",1599,1623);
$z[11][4]['name']="mid";
$z[12]=Array("field","",1714,1732);
$z[12][4]['name']="body";
$z[13]=Array("include","",1777,1814);
$z[13][4]['filename']="footer.htm";

?>