<?php
$z[0]=Array("include","",521,556);
$z[0][4]['filename']="head.htm";
$z[1]=Array("myad","",748,773);
$z[1][4]['name']="index";
$z[2]=Array("arclist","\r\n<div class=\"col-md-3 col-xs-12 row-img\">\r\n<a href=\"[field:arcurl/]\">\r\n[field:image/]\r\n<h4>[field:title/]</h4>\r\n<p>[field:info /]...</p>\r\n</a>\r\n</div>\r\n",937,1179);
$z[2][4]['row']="4";
$z[2][4]['typeid']="1";
$z[2][4]['imgwidth']="263";
$z[2][4]['imgheight']="155";
$z[2][4]['titlelen']="50";
$z[3]=Array("arclist","\r\n<div class=\"col-md-5 col-xs-12 list-bgimg-0[field:global name=autoindex/]\">\r\n<a href=\"[field:arcurl/]\"><h4>[field:title/]...</h4>\r\n<p>[field:info /]...</p></a>\r\n</div>\r\n",1543,1777);
$z[3][4]['row']="4";
$z[3][4]['typeid']="3";
$z[3][4]['titlelen']="26";
$z[4]=Array("arclist","\r\n<div class=\"col-md-4 col-xs-12 index-future\">\r\n<a href=\"[field:arcurl/]\"><h4>[field:title/]</h4></a>\r\n<p>[field:info /]...</p>\r\n</div>\r\n",2116,2316);
$z[4][4]['row']="4";
$z[4][4]['typeid']="6";
$z[4][4]['titlelen']="40";
$z[5]=Array("include","",2522,2559);
$z[5][4]['filename']="footer.htm";

?>