<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",276,305);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",345,403);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",713,748);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",936,957);
$z[5][4]['name']="content";
$z[6]=Array("field","",1095,1124);
$z[6][4]['name']="position";
$z[7]=Array("arclist","\r\n<li>\r\n[field:array runphp='yes']@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}'><img src='{@me['litpic']}' class='img-responsive'/></a>\");[/field:array]\r\n<h5>[field:title/]</h5>\r\n<p>[field:description/]...</p>\r\n</li>\r\n",1304,1636);
$z[7][4]['pagesize']="100";
$z[7][4]['flag']="p";
$z[7][4]['imgwidth']="314";
$z[7][4]['imgheight']="208";
$z[7][4]['titlelen']="54";
$z[8]=Array("include","",1682,1719);
$z[8][4]['filename']="footer.htm";

?>