<?php
$z[0]=Array("field","",189,208);
$z[0][4]['name']="title";
$z[1]=Array("global","",209,235);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",276,305);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",345,403);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",713,748);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",936,957);
$z[5][4]['name']="content";
$z[6]=Array("field","",1116,1145);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n<div class=\"media\">\r\n<div class=\"media-left\"><div class=\"wp-time\">[field:pubdate function=\"GetDateMk(@me)\"/]</div></div>\r\n<div class=\"media-body\">\r\n<a href=\"[field:arcurl/]\">\r\n<h4>[field:title/]</h4>\r\n<p>[field:description/]...<font class=\"pull-right\">[详细阅读]</font></p>\r\n</a>\r\n</div>\r\n</div>\r\n",1302,1642);
$z[7][4]['pagesize']="10";
$z[8]=Array("include","",1677,1714);
$z[8][4]['filename']="footer.htm";

?>