<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5oub55Sf5Yqo5oCB');
$cfg_Cs[2]=array(0,1,1,'5oub55Sf5pS/562W');
$cfg_Cs[3]=array(0,1,1,'5oub55Sf5a2m5qCh');
$cfg_Cs[4]=array(0,1,1,'6Ieq5Li75oub55Sf55+l6K+G');
$cfg_Cs[5]=array(0,1,1,'6Ieq5Li75oub55Sf5Z+56K6t');
$cfg_Cs[6]=array(5,1,1,'5Z+56K6t5byA54+t5Yqo5oCB');
$cfg_Cs[7]=array(0,1,1,'546w5Luj5a2m5b6S5Yi254+t');
$cfg_Cs[8]=array(0,1,1,'6IGU57O75oiR5Lus');
?>